### PR TITLE
[GLUTEN-4748][VL] Fix JNI array elements memory leak

### LINKED ISSUE #4748: [VL] JNI code memory leak when getting array elements
Some JNI code calls `Get<PrimitiveType>ArrayElements` but not calls `Release<PrimitiveType>ArrayElements` after that. This leaks memory while a session is long-running and serving a lot of queries.

Probably related to https://github.com/oap-project/gluten/issues/4144 (requires confirmation)

Ref: https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#Get_PrimitiveType_ArrayElements_routines

### PR DESCRIPTION
**Pull request by zhztheplayer**
This fixes #4748

Introduce a set of `gluten::get<primitive-type>ArrayElementsSafe` functions that would release the gotten array elements while the returned object is destructed. So user would not need to manually release the array elements which can be easily forgotten during programming.

### CODE REVIEW

**Comment by zhztheplayer** [comment]
@FelixYBW @zhouyuan

File: cpp/core/jni/JniWrapper.cc [hunk 1]
```diff
@@ -354,11 +356,10 @@ JNIEXPORT void JNICALL Java_io_glutenproject_vectorized_PlanEvaluatorJniWrapper_
   JNI_METHOD_START
 
   auto len = env->GetArrayLength(path);
-  jbyte* bytes = env->GetByteArrayElements(path, 0);
-  std::string pathStr(reinterpret_cast<char*>(bytes), len);
+  auto safeArray = gluten::getByteArrayElementsSafe(env, path);
+  std::string pathStr(reinterpret_cast<char*>(safeArray.elems()), len);
   auto ctx = gluten::getRuntime(env, wrapper);
   ctx->injectWriteFilesTempPath(pathStr);
-  env->ReleaseByteArrayElements(path, bytes, JNI_ABORT);
```
Comment (zhouyuan) [inline cpp/core/jni/JniWrapper.cc:361]: does this mean the `env->ReleaseByteArrayElements` not work as expected?

**Review by zhouyuan — APPROVED** [review]
👍

File: cpp/core/jni/JniWrapper.cc (hunk 1 above)
Comment (zhztheplayer) [reply cpp/core/jni/JniWrapper.cc:361]: It should work but some of our calls to `Get` doesn't have a corresponding call to `Release`. So this code was a good case not leading to memory leak.

Comment (zhztheplayer) [reply cpp/core/jni/JniWrapper.cc:361]: As a comparison the code in `nativeCreateKernelWithIterator` may leak considerable amount of memory since it's called frequently and missed several `Release` calls.
