### PR TITLE
[GLUTEN-11341][CORE] Support Scala 2.13 with IntelliJ IDE

### LINKED ISSUE #11341: Support Java 17 and scala 2.13 with Intellij IDE
### Problem description

Even after merging https://github.com/apache/incubator-gluten/pull/11198, we still cannot use the IntelliJ compiler, which makes incremental builds in the IntelliJ IDE impossible—forcing us to run Maven build every time and significantly wasting development time.

for example:
```
scala: Failed to parse `-Wconf` configuration: List(msg=^(?=.*?a value of type)(?=.*?cannot also be).+$:s, cat=unchecked&msg=eliminated by erasure:s, cat=unchecked&msg=outer reference:s, cat=deprecation&msg=procedure syntax is deprecated:e, msg=method without a parameter list overrides a method with a single empty one:s, msg=method with a single empty parameter list overrides method without any parameter list:s, msg=Auto-application to \`\(\)\` is deprecated:s, msg=^(?=.*?Widening conversion from)(?=.*?is deprecated because it loses precision).+$:s, msg=^(?=.*?method|value|type|object|trait|inheritance)(?=.*?deprecated)(?=.*?since 2.13).+$:s, cat=other-nullary-override:wv, cat=lint-multiarg-infix:wv, cat=scaladoc:wv, any:e, cat=deprecation:wv, cat=feature:w, cat=unchecked:w, cat=deprecation:ws, cat=feature:ws, cat=optimizer:ws)
Unknown category: `lint-multiarg-infix`
```

### System information

All

### CMake log

```bash

```

### PR DESCRIPTION
**Pull request by baibaichen**
Fixes #11341

## What changes were proposed in this pull request?

This PR includes several improvements for Scala 2.13 compatibility and code modernization:

| Change | Description | Files |
|--------|-------------|-------|
| Update Java compiler release version | Changed from hardcoded `8` to `${java.version}` in the Scala 2.13 profiler to align with `maven.compiler.target` | `pom.xml` |
| Replace deprecated file reading method | Migrated from deprecated `fileToString` to `Files.readString` in `GlutenSQLQueryTestSuite` (see https://github.com/apache/spark/pull/51911) | `gluten-ut/spark40/src/test/scala/org/apache/spark/GlutenSQLQueryTestSuite.scala` |
| Fix symbol literal deprecation | Refactored to use `Symbol()` for column references to fix compilation error in Scala 2.13 with IntelliJ compiler | `GlutenDataSourceV2Suite.scala`, `ClickHouseAdaptiveQueryExecSuite.scala`, `VeloxAdaptiveQueryExecSuite.scala` |
| Suppress warnings | Added suppressions for `ContextAwareIterator` initialization and `ContentFile::path` warnings in Scala 2.13 | `ColumnarArrowEvalPythonExec.scala`, `GlutenIcebergSourceUtil.scala` |
| Remove obsolete suppressions | Removed suppression for lint-multiarg-infix warnings from pom.xml (see https://github.com/apache/spark/pull/43332) | `pom.xml` |

## Why are the changes needed?

These changes are necessary to:
- Maintain compatibility with Scala 2.13 and IntelliJ compiler to accelerate development speed
- Remove deprecated code that was removed from Spark codebase
- Improve build configuration consistency

## How was this patch tested?
- Existing test suites
- Manual testing

### CODE REVIEW

File: gluten-ut/spark40/src/test/scala/org/apache/spark/sql/execution/adaptive/velox/VeloxAdaptiveQueryExecSuite.scala [hunk 1]
```diff
@@ -986,15 +987,16 @@ class VeloxAdaptiveQueryExecSuite extends AdaptiveQueryExecSuite with GlutenSQLT
 
         // Repartition with non-default partition num specified.
         checkSMJ(
-          df.repartition(4, 'b),
+          df.repartition(4, Symbol("b")),
```
Comment (jinchengchenghh) [inline gluten-ut/spark40/src/test/scala/org/apache/spark/sql/execution/adaptive/velox/VeloxAdaptiveQueryExecSuite.scala]: Can we use col("b")? The warning may be caused by b with single quote

File: gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala [hunk 2]
```diff
@@ -50,6 +51,7 @@ object GlutenIcebergSourceUtil {
     }
   }
 
+  @nowarn
```
Comment (jinchengchenghh) [inline gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala:54]: What's the warning message? Can we fix the warning?

File: gluten-ut/spark40/src/test/scala/org/apache/spark/sql/execution/adaptive/velox/VeloxAdaptiveQueryExecSuite.scala (hunk 1 above)
Comment (jinchengchenghh) [reply gluten-ut/spark40/src/test/scala/org/apache/spark/sql/execution/adaptive/velox/VeloxAdaptiveQueryExecSuite.scala]: Syntax | Valid | Notes
-- | -- | --
df.repartition(4, 'b) | ✅ | Old-style, works
df.repartition(4, Symbol("b")) | ✅ | Same as above
df.repartition(4, col("b")) | ✅ | Recommended
df.repartition(4, 'b), | ❌ | Syntax error

File: gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala (hunk 2 above)
Comment (baibaichen) [reply gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala:54]: `org.apache.iceberg.ContentFile::path()` is marked as `deprecated`. Without introducing a shim, it's hard to fix properly, so we'll suppress the warning for now.

```scala
        asFileScanTask(tasks.toList).foreach {
          task =>
            paths.add(
              BackendsApiManager.getTransformerApiInstance
                .encodeFilePathIfNeed(task.file().path().toString))  // => deprecated
``` 

Additionally, `@nowarn` can only be added before method names; it cannot be applied before individual statements.

Comment (jinchengchenghh) [reply gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala:54]: As the comment indicates, please use location
```
  /**
   * Returns fully qualified path to the file, suitable for constructing a Hadoop Path.
   *
   * @deprecated since 1.7.0, will be removed in 2.0.0; use {@link #location()} instead.
   */
  @Deprecated
  CharSequence path();

  /** Return the fully qualified path to the file. */
  default String location() {
    return path().toString();
  }
```

Comment (jinchengchenghh) [reply gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala:54]: There is shim for iceberg like this PR, https://github.com/apache/incubator-gluten/pull/11146, we can accept current workaround, and fix it after https://github.com/apache/incubator-gluten/pull/11146 merge

Comment (baibaichen) [reply gluten-iceberg/src/main/scala/org/apache/iceberg/spark/source/GlutenIcebergSourceUtil.scala:54]: > As the comment indicates, please use location
> 
> ```
>   /**
>    * Returns fully qualified path to the file, suitable for constructing a Hadoop Path.
>    *
>    * @deprecated since 1.7.0, will be removed in 2.0.0; use {@link #location()} instead.
>    */
>   @Deprecated
>   CharSequence path();
> 
>   /** Return the fully qualified path to the file. */
>   default String location() {
>     return path().toString();
>   }
> ```

No, `location` doesn't work in profiles in Spark 3.3 and earlier.

**Comment by baibaichen** [comment]
Run Gluten Clickhouse CI on x86
