### PR TITLE
[GLUTEN-11692][CORE] Driver side should avoid submitting subqueries while validating file formats

### LINKED ISSUE #11692: [VL][BUG]Spark UTs from suite DynamicPartitionPruningHiveScanSuite are failing
### Backend

VL (Velox)

### Bug description

Some UTs from Spark test suite DynamicPartitionPruningHiveScanSuiteAEOff and DynamicPartitionPruningHiveScanSuiteAEOn are failing from Gluten version 1.5.1 onwards.

Error Message: 
`requirement failed: input[0, bigint, true] IN dynamicpruning#13980 has not finished`

The below are the list of UTs.

```
avoid reordering broadcast join keys to match input hash partitioning
broadcast a single key in a HashedRelation
broadcast multiple keys in a LongHashedRelation
broadcast multiple keys in an UnsafeHashedRelation
cleanup any DPP filter that isn't pushed down due to expression id clashes
different broadcast subqueries with identical children
DPP should not be rewritten as an existential join
DPP triggers only for certain types of query
nB
filtering ratio policy with stats when the broadcast pruning is disabled
Gluten - Make sure dynamic pruning works on uncorrelated queries
Gluten - SPARK-38674: Remove useless deduplicate in SubqueryBroadcastExec
join key with multiple references on the filtering plan
partition pruning in broadcast hash joins
partition pruning in broadcast hash joins with aliases
Plan broadcast pruning only when the broadcast can be reused
simple inner join triggers DPP with mock-up tables
SPARK-32659: Fix the data issue when pruning DPP on non-atomic type
SPARK-32817: DPP throws error when the broadcast side is empty
SPARK-34436: DPP support LIKE ANY/ALL expression
SPARK-34595: DPP support RLIKE expression
SPARK-34637: DPP side broadcast query stage is created firstly
SPARK-36444: Remove OptimizeSubqueries from batch of PartitionPruning
SPARK-38148: Do not add dynamic partition pruning if there exists static partition pruning
SPARK-39217: Makes DPP support the pruning side has Union
SPARK-39338: Remove dynamic pruning subquery if pruningKey's references is empty
Subquery reuse across the whole plan
```

Looks like https://github.com/apache/incubator-gluten/pull/11113 is causing the issue. Consistently reproducible.

Gluten version
Gluten 1.5.1 - latest

Spark version
4.0.x

Spark configurations

System information

### Gluten version

Gluten-1.5

### Spark version

spark-4.0.x

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

```bash

```

### PR DESCRIPTION
**Pull request by beliefer**
## What changes are proposed in this pull request?

This PR proposes to avoid submitting subqueries while validating file formats.
Fixes #11692

## How was this patch tested?

Manual tests in our product environment.

## Was this patch authored or co-authored using generative AI tooling?

'No'.

### CODE REVIEW

**Comment by beliefer** [comment]
Run Gluten Clickhouse CI on x86

**Comment by beliefer** [comment]
ping @wForget @jinchengchenghh @zhouyuan @zml1206

File: shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala [hunk 1]
```diff
@@ -173,26 +173,30 @@ abstract private[hive] class AbstractHiveTableScanExec(
...
+  // This is used on the driver side, so it is important to avoid executing subqueries
+  @transient lazy val basePrunedPartitions: Seq[HivePartition] = {
+    if (relation.prunedPartitions.nonEmpty) {
+      relation.prunedPartitions.get.map(HiveClientImpl.toHivePartition(_, hiveQlTable))
+    } else {
+      rawPartitions
+    }
+  }
+
+  @transient lazy val prunedPartitions: Seq[HivePartition] =
```
Comment (wForget) [inline shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala:185]: nit: reduce redundant judgment
```
  @transient lazy val prunedPartitions: Seq[HivePartition] =
    if (partitionPruningPred.forall(!ExecSubqueryExpression.hasSubquery(_)) ||
        (sparkSession.sessionState.conf.metastorePartitionPruning &&
          partitionPruningPred.nonEmpty))
      basePrunedPartitions
    } else {
      prunePartitions(basePrunedPartitions)
    }
```

File: gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala [hunk 2]
```diff
@@ -77,7 +77,16 @@ case class HiveTableScanExecTransformer(
     partitionWithReadFileFormats
 
   override def getDistinctPartitionReadFileFormats: Set[ReadFileFormat] =
```
Comment (wForget) [inline gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala:79]: Could you also add a comment for this method? Mark it as only for validation.

File: shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala (hunk 1 above)
Comment (beliefer) [reply shims/spark33/src/main/scala/org/apache/spark/sql/hive/execution/AbstractHiveTableScanExec.scala:185]: Are you sure?

File: gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala (hunk 2 above)
Comment (beliefer) [reply gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala:79]: I updated comments at the declaration in the `WholeStageTransformer.scala`.
