### PR TITLE
[GLUTEN-3534][CH] Fix incorrect logic of judging whether supports pre-project for the shuffle

### LINKED ISSUE #3534: [CH] Fix incorrect logic of judging whether supports pre-project for the shuffle
### Backend

CH (ClickHouse)

### Bug description

Fix incorrect logic of judging whether supports pre-project for the shuffle:

Currently when judging whether supports pre-project for the shuffle, it only check whether is `Cast` expression. It must check whether is the supported expression.

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by zzcclp**
## What changes were proposed in this pull request?

Currently when judging whether supports pre-project for the shuffle, it only check whether is Cast expression. It must check whether is the supported expression.

Close #3534.

(Fixes: #3534)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by zzcclp** [comment]
@KevinyhZou @lgbo-ustc please help to review, thanks.

File: backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala [hunk 1]
```diff
@@ -143,13 +143,7 @@ object CHBackendSettings extends BackendSettingsApi with Logging {
...
           outputPartitioning match {
             case hashPartitioning: HashPartitioning =>
-              hashPartitioning.expressions.foreach(
-                x => {
-                  if (!x.isInstanceOf[Cast]) {
-                    return false
-                  }
-                })
-              true
+              hashPartitioning.expressions.exists(x => !x.isInstanceOf[AttributeReference])
```
Comment (lgbo-ustc) [inline backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala:146]: 之前逻辑上如果是cast应该是可以支持的。这样改不是cast也不支持了？

Comment (zzcclp) [reply backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala:146]: it supports all the expression which are supported in ch backend.

Comment (zzcclp) [reply backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHBackend.scala:146]: please see the ut: https://github.com/oap-project/gluten/blob/50382047441e1bd0c921559656e682710a03e086/backends-clickhouse/src/test/scala/io/glutenproject/execution/GlutenClickHouseTPCHParquetSuite.scala#L2128C3-L2128C3

**Comment by KevinyhZou** [comment]
LGTM

**Review by baibaichen — APPROVED** [review]
LGTM
