### PR TITLE
[GLUTEN-1848][Core] Fix execute subquery repeatedly issue with ReusedSubquery when aqe is on

### LINKED ISSUE #1848: Fix execute subquery repeatedly issue with ReusedSubquery when aqe is on
**Describe the bug**
Execute subquery repeatedly with ReusedSubquery when aqe is on:

When AQE is on, spark will apply `ReuseAdaptiveSubquery` rule first, it will reuse vanilla `SubqueryBroadcastExec`, and then use gluten `ColumnarOverrides` rule to transform `Subquery`, so all `SubqueryBroadcastExec` in the `ReusedSubqueryExec` will be transformed to a new `ColumnarSubqueryBroadcastExec`, which will lead to execute `ColumnarSubqueryBroadcastExec.relationFuture` repeatedly even in the `ReusedSubqueryExec`.

When AQE is off, there is no this issue, because the `ReuseExchangeAndSubquery` rule will be applied after the `ColumnarOverrides` rule.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by zzcclp**
## What changes were proposed in this pull request?

When AQE is on, spark will apply `ReuseAdaptiveSubquery` rule first, it will reuse vanilla `SubqueryBroadcastExec`, and then use gluten `ColumnarOverrides` rule to transform Subquery, so all `SubqueryBroadcastExec` in the `ReusedSubqueryExec` will be transformed to a new `ColumnarSubqueryBroadcastExec` for each one, which will lead to execute `ColumnarSubqueryBroadcastExec.relationFuture` repeatedly even in the `ReusedSubqueryExec`.

When AQE is off, there is no this issue, because the ReuseExchangeAndSubquery rule will be applied after the ColumnarOverrides rule.

Close #1848.

(Fixes: #1848)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

File: gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala [hunk 1]
```diff
@@ -501,13 +502,19 @@ object FilterHandler {
 
   // Separate and compare the filter conditions in Scan and Filter.
   // Push down the left conditions in Filter into Scan.
-  def applyFilterPushdownToScan(plan: FilterExec): SparkPlan = plan.child match {
+  def applyFilterPushdownToScan(
+    plan: FilterExec,
+    reusedSubqueriesMap: mutable.Map[SparkPlan, BaseSubqueryExec],
+    reuseSubaquery: Boolean): SparkPlan = plan.child match {
```
Comment (Yohahaha) [inline gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala:508]: nit: reuseSubaquery -> reuseSubquery

File: gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala [hunk 2]
```diff
@@ -582,7 +584,10 @@ object ExpressionConverter extends SQLConfHelper with Logging {
    * @param partitionFilters
    * @return
    */
-  def transformDynamicPruningExpr(partitionFilters: Seq[Expression]): Seq[Expression] = {
+  def transformDynamicPruningExpr(
+    partitionFilters: Seq[Expression],
+    reusedSbqueriesMap: mutable.Map[SparkPlan, BaseSubqueryExec],
+    reuseSuquery: Boolean): Seq[Expression] = {
```
[the remark this answers is not in the document]
Comment (zzcclp) [reply gluten-core/src/main/scala/io/glutenproject/expression/ExpressionConverter.scala]: Done, thx.

File: gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala (hunk 1 above)
Comment (zzcclp) [reply gluten-core/src/main/scala/io/glutenproject/execution/BasicPhysicalOperatorTransformer.scala]: Done, thx.

File: gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala [hunk 3]
```diff
@@ -499,9 +502,9 @@ case class TransformPreOverrides(isAdaptiveContextOrTopParentExchange: Boolean)
    */
   def applyScanTransformer(plan: SparkPlan): SparkPlan = plan match {
     case plan: FileSourceScanExec =>
-      val newPartitionFilters = {
-        ExpressionConverter.transformDynamicPruningExpr(plan.partitionFilters)
-      }
+      val newPartitionFilters = ExpressionConverter.transformDynamicPruningExpr(
+        plan.partitionFilters,
+        conf.adaptiveExecutionEnabled && conf.subqueryReuseEnabled)
```
Comment (PHILO-HE) [inline gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala:507]: As we know, spark has its own logic to check a given plan to determine whether it should go into AQE logic (see `shouldApplyAQE`&`supportAdaptive` in spark code), not just depending on the config for `adaptiveExecutionEnabled`. So previously, we have a hack approach to discover AQE context at runtime, see `isAdaptiveContext` at `ColumnarOverride.scala`. Should we use it to confirm AQE is applied? Thanks!

Comment (PHILO-HE) [reply gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala:507]: I note `transformDynamicPruningExpr` will also check whether `newIn.child` is `AdaptiveSparkPlanExec`. If this check confirms AQE is applied with no exceptional case, the proposed patch may work well. Thanks!

Comment (zzcclp) [reply gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala]: Done, use `isAdaptiveContext` instead of the `adaptiveExecutionEnabled`

**Review by rui-mo — APPROVED** [review]
Verified the perf on Jenkins.
