### PR TITLE
[GLUTEN-10966][VL] Support codegen for ArrowProjection

### LINKED ISSUE #10966: [VL] Support codegen for ArrowProjection
### Description

During upgrade from gluten 1.2 to 1.5, I found that PartialProject with complex expressions could cause performance regressions. Supporting codegen for ArrowProjection should improve performance.

gluten 1.2:

Image

gluten 1.5:

Image

### Gluten version

Gluten-1.5

### PR DESCRIPTION
**Pull request by wForget**
## What changes are proposed in this pull request?

Support codegen for ArrowProjection. Mostly copied from [GenerateMutableProjection](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/codegen/GenerateMutableProjection.scala), some changes have been commented.

closes #10966

## How was this patch tested?

Verified in our internal branch-1.5 environment, results are consistent and has benefits.

image

Before (branch-1.5.0 without this change):

image

After (branch-1.5.0 with this change):

image

### CODE REVIEW

File: gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala [hunk 1]
```diff
@@ -0,0 +1,155 @@
...
+            """.stripMargin,
+            FalseLiteral)
+        }
+        val update = CodeGenerator.updateColumn(
+          "mutableRow",
+          e.dataType,
+          i,
+          ExprCode(isNull, value),
+          e.nullable,
+          isVectorized = true)
```
Comment (wForget) [inline gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala]: set `isVectorized=true`

File: gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+
+    val codeBody = s"""
+      public java.lang.Object generate(Object[] references) {
+        return new SpecificArrowProjection(references);
+      }
+
+      class SpecificArrowProjection extends ${classOf[BaseArrowProjection].getName} {
+
+        private Object[] references;
+        private ArrowColumnarRow mutableRow;
```
Comment (wForget) [inline gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala]: change row type to `ArrowColumnarRow`

File: gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala [hunk 3]
```diff
@@ -0,0 +1,158 @@
...
+
+      class SpecificArrowProjection extends ${classOf[BaseArrowProjection].getName} {
+
+        private Object[] references;
+        private ${classOf[ArrowColumnarRow].getName} mutableRow;
+        ${ctx.declareMutableStates()}
+
+        public SpecificArrowProjection(Object[] references) {
+          this.references = references;
+          mutableRow = null;
```
Comment (wForget) [inline gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala:116]: set mutableRow to null, mutableRow will be assigned through the target method

File: gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+          (
+            s"""
+               |${ev.code}
+               |$value = ${ev.value};
+            """.stripMargin,
+            FalseLiteral)
+        }
+        // update value into intermediate
+        val update = CodeGenerator
+          .updateColumn("intermediate", e.dataType, i, ExprCode(isNull, value), e.nullable)
```
Comment (wForget) [inline gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala:92]: update value into intermediate row

File: gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala [hunk 5]
```diff
@@ -0,0 +1,158 @@
...
+    val codeBody = s"""
+      public java.lang.Object generate(Object[] references) {
+        return new SpecificArrowProjection(references);
+      }
+
+      class SpecificArrowProjection extends ${classOf[BaseArrowProjection].getName} {
+
+        private Object[] references;
+        private ${classOf[ArrowColumnarRow].getName} mutableRow;
+        private ${classOf[GenericInternalRow].getName} intermediate;
```
Comment (wForget) [inline gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala:111]: add an intermediate row

File: gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala [hunk 6]
```diff
@@ -0,0 +1,158 @@
...
+        }
+
+        public java.lang.Object apply(java.lang.Object _i) {
+          InternalRow ${ctx.INPUT_ROW} = (InternalRow) _i;
+          $evalSubexpr
+          $allProjections
+          // copy all the results into intermediate
+          $allUpdates
+          // write intermediate to mutableRow
+          mutableRow.writeRow(intermediate);
```
Comment (wForget) [inline gluten-arrow/src/main/scala/org/apache/gluten/expression/GenerateArrowProjection.scala:143]: write intermediate to mutableRow
