### PR TITLE
[GLUTEN-2625][VL] Fix: Velox shuffle reader / Velox Parquet data-source memory leak 

### LINKED ISSUE #2625: Memory leak found on TPCDS
**Describe the bug**
We found memory leak on TPCDS queries. We track the memory usage during the testing process and found that the memory used by the Executor keeps increasing gradually.

**To Reproduce**
```
The latest gluten commit is `d28c3f9940b31d4f9318cce8979527896258b6c9`
The offheap memory is 25G with 8 cores.
The tpcds data size is 10TB and the partitions is 1048.
```

### PR DESCRIPTION
**Pull request by zhztheplayer**
This patch fixed the memory leaks: the arrow schema is not correctly released on shuffle reader.

This resolves #2625

### CODE REVIEW

**Review by jinchengchenghh — APPROVED** [review]

File: cpp/velox/shuffle/VeloxShuffleReader.cc [hunk 1]
```diff
@@ -314,9 +315,7 @@ VeloxShuffleReader::VeloxShuffleReader(
     std::shared_ptr<arrow::MemoryPool> pool,
     std::shared_ptr<memory::MemoryPool> veloxPool)
     : Reader(in, schema, options, pool), veloxPool_(std::move(veloxPool)) {
-  ArrowSchema cSchema;
-  GLUTEN_THROW_NOT_OK(arrow::ExportSchema(*schema, &cSchema));
-  rowType_ = asRowType(importFromArrow(cSchema));
```
Comment (zhouyuan) [inline cpp/velox/shuffle/VeloxShuffleReader.cc:319]: so, the leakage is here: should release cSchema ?

File: cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc [hunk 2]
```diff
@@ -47,7 +47,7 @@ VeloxColumnarBatchSerializer::VeloxColumnarBatchSerializer(
   // serializeColumnarBatches don't need rowType_
   if (cSchema != nullptr) {
     rowType_ = asRowType(importFromArrow(*cSchema));
-    ArrowSchemaRelease(cSchema);
+    ArrowSchemaRelease(cSchema); // otherwise the c schema leaks memory
   }
```
Comment (zhouyuan) [inline cpp/velox/operators/serializer/VeloxColumnarBatchSerializer.cc:51]: not a leak, as it's released?

File: cpp/velox/utils/VeloxArrowUtils.cc [hunk 3]
```diff
@@ -36,7 +36,7 @@ arrow::Status MyMemoryPool::Allocate(int64_t size, int64_t alignment, uint8_t**
   if (bytes_allocated() + size > capacity_) {
     return arrow::Status::OutOfMemory("malloc of size ", size, " failed");
   }
-  RETURN_NOT_OK(pool_->Allocate(size, out));
+  RETURN_NOT_OK(pool_->Allocate(size, alignment, out));
```
Comment (zhouyuan) [inline cpp/velox/utils/VeloxArrowUtils.cc:39]: need to do an aligned allocate, is this also related with the leakage?

**Comment by zhouyuan** [comment]
@zhztheplayer thanks for the quick fix!

File: cpp/velox/utils/VeloxArrowUtils.cc (hunk 3 above)
Comment (zhztheplayer) [reply cpp/velox/utils/VeloxArrowUtils.cc:39]: No... It's just some code looking buggy so I fixed in passing. The code is only used for testing afaik.

File: cpp/velox/shuffle/VeloxShuffleReader.cc (hunk 1 above)
Comment (zhztheplayer) [reply cpp/velox/shuffle/VeloxShuffleReader.cc:319]: Yes. It's the leakage source in this case. Gluten creates a lot of this reader instance to handle Spark's shuffle read fetches.
