### PR TITLE
[GLUTEN-10181][CH] Not reuse a `HashJoinwith` when have different `BroadCastHashJoinContext`

### LINKED ISSUE #10181: [CH] Reusing a `HashJoin` with different `BroadCastHashJoinContext`  may lead to unexpected behavior
### Backend

CH (ClickHouse)

### Bug description

fix https://github.com/Kyligence/ClickHouse/commit/e5b9e10de820ea694924caabcb9a425720212599. 

### Gluten version

_No response_

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

```bash

```

### PR DESCRIPTION
**Pull request by lgbo-ustc**
… parameters

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

A way to fix #10181, and don't change CH kernel.

Fixes: #10181

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

unit tests

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

File: backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/joins/ClickHouseBuildSideRelation.scala [hunk 1]
```diff
@@ -44,31 +44,41 @@ case class ClickHouseBuildSideRelation(
...
+        (existHashTableData, this)
       } else {
-        (StorageJoinBuilder.nativeCloneBuildHashTable(hashTableData), null)
+        (StorageJoinBuilder.nativeCloneBuildHashTable(existHashTableData), null)
       }
     }
 
   def reset(): Unit = synchronized {
-    hashTableData = 0
+    existHashTableData = 0
```
Comment (baibaichen) [inline backends-clickhouse/src/main/scala/org/apache/spark/sql/execution/joins/ClickHouseBuildSideRelation.scala:73]: reset existBroadCastHashJoinContext ?

**Review by baibaichen — APPROVED** [review]
