### PR TITLE
[Gluten-161] The children of BaseJoinExec should insert WholeStageTransformerExec separately

### LINKED ISSUE #161: The children of BaseJoinExec should insert WholeStageTransformerExec separately
Currently, the strategy of inserting 'WholeStageTransformer' only meet the shuffle exchange scenario, when there is a join operator, it also needs to insert 'WholeStageTransformer' for the children of the join operator.

Please refer to : [WholeStageCodegenExec.scala](https://github.com/apache/spark/blob/66648e96e4283223003c80a1a997325bbd27f940/sql/core/src/main/scala/org/apache/spark/sql/execution/WholeStageCodegenExec.scala#L893)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by zzcclp**
Currently, the strategy of inserting 'WholeStageTransformer' only meet the shuffle exchange scenario, when there is a join operator, it also needs to insert 'WholeStageTransformer' for the children of the join operator.

Please refer to : [WholeStageCodegenExec.scala](https://github.com/apache/spark/blob/66648e96e4283223003c80a1a997325bbd27f940/sql/core/src/main/scala/org/apache/spark/sql/execution/WholeStageCodegenExec.scala#L893)

Close #161 .

## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by marin-ma** [comment]
Could you explain why we need to seperate the WholeStageTransformer for join and its children? If they are in the same transform context, they can be off-loaded to backend together.

**Comment by zzcclp** [comment]
> 

1. Currently, the

**Comment by zzcclp** [comment]
> Could you explain why we need to seperate the WholeStageTransformer for join and its children? If they are in the same transform context, they can be off-loaded to backend together.

1. Keep the same separation 'WholeStageXXX' strategy as the Spark, please see the code: [WholeStageCodegenExec.scala](https://github.com/apache/spark/blob/66648e96e4283223003c80a1a997325bbd27f940/sql/core/src/main/scala/org/apache/spark/sql/execution/WholeStageCodegenExec.scala#L893)
2. If keep the children of the join in one 'WholeStageTransformer', there are some errors happen:
   1). in case there is one child of the join in the same 'WholeStageTransformer', for example, 'buildPlan', calling ShuffledHashJoinExecTransformer.columnarInputRDDs will throw NPE, because the 'buildPlan' will call 'columnarInputRDDs' recursively, the last one node is 'BatchScanExecTransformer' and will return null;
  2). in case two children of the join are all in the same 'WholeStageTransformer', it will generate substrait plan in the first stage ( NativeWholeStageColumnarRDD ) but not the final stage ( WholeStageZippedPartitionsRDD ), on the other hand, the read rel node of two children will be set the same 'localFiles'.

File: jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala [hunk 1]
```diff
@@ -121,13 +122,19 @@ case class ColumnarCollapseCodegenStages(
     plan match {
       case p if !supportTransform(p) =>
         new ColumnarInputAdapter(insertWholeStageTransformer(p))
+      // The children of BaseJoinExec should do transformer separately.
+      case j if j.isInstanceOf[BaseJoinExec] =>
+        j.withNewChildren(j.children.map(c => insertWholeStageTransformer(c)))
```
Comment (marin-ma) [inline jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala:127]: The final Spark plan tree seems not right. Maybe something's missing here:
```
j.withNewChildren(j.children.map(c =>
    new ColumnarInputAdapter(insertWholeStageTransformer(c))))
```

**Comment by marin-ma** [comment]
I see. Indeed, separating the children into different substrait plan can fix this. Although I still have no idea why the WholeStageCodegenTransformer must be consistent with the behavior of Spark's codegen, but basically, I think:
1). is due to the `getChild` function in `ShuffledHashjoinExecTransformer` only returns streamed plan, which is unreasonable and if it's called in other code paths, it will also return unexpected results.
2). The children will generate substrait plan in the first stage ( NativeWholeStageColumnarRDD ) only when the they are in the first stage. But since NativeWholeStageColumnarRDD doen't support multiple scan nodes, seperating the children in first stages can be the solution.

File: jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala [hunk 2]
```diff
@@ -121,13 +122,19 @@ case class ColumnarCollapseCodegenStages(
...
       case p =>
         p.withNewChildren(p.children.map(insertInputAdapter))
     }
   }
 
   private def insertWholeStageTransformer(plan: SparkPlan): SparkPlan = {
     plan match {
+      // The children of BaseJoinExec should do transformer separately.
+      case t: TransformSupport if t.isInstanceOf[BaseJoinExec] =>
+        t.withNewChildren(t.children.map(insertWholeStageTransformer))
```
Comment (marin-ma) [inline jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala:137]: This seems not right and should be removed. We need to insert WholeStageTransformerExec for Join.

File: jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala (hunk 1 above)
Comment (zzcclp) [reply jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala]: Fixed

File: jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala (hunk 2 above)
Comment (zzcclp) [reply jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala]: Fixed

**Comment by marin-ma** [comment]
https://github.com/oap-project/gluten/blob/ee362571ca5304c1cc01fb8ceacd1b8a9d8a2eb1/jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala#L136-L138

We need to modify this to:
```
case t: TransformSupport =>
  WholeStageTransformerExec(insertInputAdapter(t))(codegenStageCounter.incrementAndGet())
```
Or else in the case of two consecutive hash joins, the generated plan would be wrong.

**Comment by zzcclp** [comment]
> https://github.com/oap-project/gluten/blob/ee362571ca5304c1cc01fb8ceacd1b8a9d8a2eb1/jvm/src/main/scala/org/apache/spark/sql/execution/ColumnarCollapseCodegenStages.scala#L136-L138
> 
> We need to modify this to:
> 
> ```
> case t: TransformSupport =>
>   WholeStageTransformerExec(insertInputAdapter(t))(codegenStageCounter.incrementAndGet())
> ```
> 
> Or else in the case of two consecutive hash joins, the generated plan would be wrong.

Fixed.

**Comment by marin-ma** [comment]
Verified locally. LGTM.

**Comment by rui-mo** [comment]
Working on the verification. BTW, could you paste the picture of the query plan here to help readers understand the issue you are fixing?

**Comment by zzcclp** [comment]
After this pr, the new spark plans are below:

in case the children of the join are not ShuffleExchange:
tmp2

in case one child of the join are ShuffleExchange:
tmp

in case the children of the join are ShuffleExchange:
tmp1

**Comment by rui-mo** [comment]
Looks like we do not support the operators in the blue lines to be merged into a whole stage transformer, right?
plan

**Review by rui-mo — APPROVED** [review]

**Comment by rui-mo** [comment]
Verified locally.

**Comment by zzcclp** [comment]
> Looks like we do not support the operators in the blue lines to be merged into a whole stage transformer, right? plan

Yes, the Apache Spark also does like this.
