### PR TITLE
[GLUTEN-11062][CORE] Supports mixed input format for partitioned Hive table

### LINKED ISSUE #11062: [VL] No magic bytes found at end of the Parquet file
### Backend

VL (Velox)

### Bug description

We have some Hive table with ORC format. Users want convert the Hive table from ORC format to Parquet format.  In the transition stage, some partitions are already converted to Parquet format, but the others not.

We execute the SQL, such as:
`select * from intermediate_state_table;`
It is OK when we using Spark, but it is bad when using Gluten. We get the following error.

```
Caused by: org.apache.gluten.exception.GlutenException: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: No magic bytes found at end of the Parquet file
Retriable: False
Expression: strncmp(copy.data() + readSize - 4, "PAR1", 4) == 0
Context: Split [Hive: hdfs://path/intermediate_state_table/20240818/part-00000-cc17cd1a-35a6-4ec6-8694-3dcdcb95ccfc-c000 0 - 2545077] Task Gluten_Stage_0_TID_160_VTID_1
Additional Context: Operator: TableScan[0] 0
Function: loadFileMetaData
File: /home/hadoop/gluten/ep/build-velox/build/velox_ep/velox/dwio/parquet/reader/ParquetReader.cpp
Line: 216
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorEPKcEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox7parquet10ReaderBase16loadFileMetaDataEv
# 4  _ZN8facebook5velox7parquet10ReaderBaseC1ESt10unique_ptrINS0_4dwio6common13BufferedInputESt14default_deleteIS6_EERKNS5_13ReaderOptionsE
# 5  _ZN8facebook5velox7parquet13ParquetReaderC2ESt10unique_ptrINS0_4dwio6common13BufferedInputESt14default_deleteIS6_EERKNS5_13ReaderOptionsE
# 6  _ZN8facebook5velox7parquet20ParquetReaderFactory12createReaderESt10unique_ptrINS0_4dwio6common13BufferedInputESt14default_deleteIS6_EERKNS5_13ReaderOptionsE
# 7  _ZN8facebook5velox9connector4hive11SplitReader12createReaderEv
# 8  _ZN8facebook5velox9connector4hive11SplitReader12prepareSplitESt10shared_ptrINS0_6common14MetadataFilterEERNS0_4dwio6common17RuntimeStatisticsE
# 9  _ZN8facebook5velox9connector4hive14HiveDataSource8addSplitESt10shared_ptrINS1_14ConnectorSplitEE
# 10 _ZN8facebook5velox4exec9TableScan9getOutputEv
# 11 _ZZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEEENKUlvE8_clEv
# 12 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE
# 13 _ZN8facebook5velox4exec6Driver4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 14 _ZN8facebook5velox4exec4Task4nextEPN5folly10SemiFutureINS3_4UnitEEE
# 15 _ZN6gluten24WholeStageResultIterator4nextEv
# 16 Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeHasNext
# 17 0x00007f48b5018747

    at org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
    at org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNext0(ColumnarBatchOutIterator.java:57)
    at org.apache.gluten.iterator.ClosableIterator.hasNext(ClosableIterator.java:39)
    ... 27 more
```

### Gluten version

Gluten 1.3 ~ 1.6

### Spark version

3.2.2

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

```bash

```

### PR DESCRIPTION
**Pull request by beliefer**
## What changes are proposed in this pull request?

This PR proposes to supports mixed input format for partitioned Hive table.
Fixes #11062

## How was this patch tested?

Manual tests in our production environment.

### CODE REVIEW

File: gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala [hunk 1]
```diff
@@ -82,23 +82,52 @@ case class HiveTableScanExecTransformer(
...
       }
-      hivePartitionConverter.createFilePartition(tableLocation)
+      Seq((hivePartitionConverter.createFilePartition(tableLocation), fileFormat))
+    } else if (existsMixedInputFormat) {
+      // Currently, we only consider the case where Hive table mix two different input format.
+      val (partitions1, partitions2) =
+        prunedPartitions.partition(_.getInputFormatClass == tableDesc.getInputFileFormatClass)
+      assert(partitions2.forall(_.getInputFormatClass == partitions2.head.getOutputFormatClass))
+
+      val anotherFileFormat = getFileFormat(
```
Comment (jinchengchenghh) [inline gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala]: Can we add ReadFileFormat for each partition? This can support partition with any file format. There may be more than 2 file format

Comment (beliefer) [reply gluten-substrait/src/main/scala/org/apache/spark/sql/hive/HiveTableScanExecTransformer.scala]: Thanks for your comments. I will try it tomorrow.

File: gluten-substrait/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala [hunk 2]
```diff
@@ -123,8 +123,8 @@ abstract class FileSourceScanExecTransformerBase(
 
   override def getMetadataColumns(): Seq[AttributeReference] = metadataColumns
 
-  override def getPartitions: Seq[Partition] = {
-    BackendsApiManager.getTransformerApiInstance
+  override def getPartitions: Seq[(Seq[Partition], ReadFileFormat)] = {
```
Comment (wForget) [inline gluten-substrait/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala]: Would it be better to add a new implementation of Partition with ReadFileFormat? That would make it easier for us to extend partition with schema in the future.

Comment (beliefer) [reply gluten-substrait/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala]: Sounds good to me.

Comment (wForget) [reply gluten-substrait/src/main/scala/org/apache/gluten/execution/FileSourceScanExecTransformer.scala]: I mean adding a new Partition class, but the current way of adding a new method also looks good to me.

**Review by wForget — APPROVED** [review]
Thanks @beliefer , LGTM. Maybe later we can also support mixed schema for partitioned hive table.

**Comment by beliefer** [comment]
> Could you help add a unit test to cover this feature?

Because the Hive table created with Hive cli. I don't know how to add it.

**Comment by beliefer** [comment]
cc @zhztheplayer @FelixYBW @zhouyuan

**Comment by jackylee-ch** [comment]
> Because the Hive table created with Hive cli. I don't know how to add it.

@beliefer You can try to use alterTable api to change the hive table. 

Here is a little example, It should work well with this pr.
```scala
  spark.range(0, 10).write.mode("overwrite").parquet("file:///tmp/test_parquet")
  spark.range(10, 20).write.mode("overwrite").orc("file:///tmp/test_orc")
  spark.sql("create external table demo (id long) partitioned by (part string) stored as orc location 'file:///tmp/demo'")
  spark.sql("alter table demo add partition(part=2) location 'file:///tmp/test_orc'")
  val table = spark.sessionState.catalog.getTableMetadata(TableIdentifier("demo"))
  val newTable = table.copy(storage =
    table.storage.copy(
      serde = Some("org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"),
      inputFormat = Some("org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"),
      outputFormat = Some("org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat")
    ))
  spark.sessionState.catalog.alterTable(newTable)
  spark.sql("alter table demo add partition(part=1) location 'file:///tmp/test_parquet'")
  spark.table("demo").show()
```

**Comment by beliefer** [comment]
@jackylee-ch Thank you. I tried. But the partition format of part 1 still is orc even if the underlying data format is orc.

**Comment by beliefer** [comment]
@jinchengchenghh @jackylee-ch I already added test case with Hive Cli.
cc @wForget

**Comment by jackylee-ch** [comment]
> @jackylee-ch Thank you. I tried. But the partition format of part 1 still is orc even if the underlying data format is orc.

The partition format for part 1 should be Parquet. Anyway, the current test suite looks good to me.

**Comment by beliefer** [comment]
> > @jackylee-ch Thank you. I tried. But the partition format of part 1 still is orc even if the underlying data format is orc.
> 
> The partition format for part 1 should be Parquet. Anyway, the current test suite looks good to me.

I'm sorry! I said wrong. the partition format of part 1 still is parquet even if the underlying data format is orc.

**Comment by beliefer** [comment]
The four fail tests is not related to this PR. They still fail in other PR.
