### PR TITLE
[Gluten-1124] Close connector preload split on current memory management.

### LINKED ISSUE #1124: Memory management not suitable with Velox split preload feature.
**Describe the bug**
Velox has split preload feature when connector holds a valid executor, but it may outlive the task with extra memory allocation.
Gluten's `WrappedVeloxMemoryPool` assume all memory should be released in its destructor.

**To Reproduce**
Add this code in `VeloxInitializer` before construct hive connector.
```
ioExecutor_ = std::make_unique<folly::IOThreadPoolExecutor>(5));
```

Execute tpch q11, or sql with join but I'm not test.

```
Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (0 vs. 192) Memory pool should be destroyed only after all allocated memory has been freed. Remaining bytes allocated: 192, cumulative bytes allocated: 1048576, number of allocations: 1
Retriable: False
Expression: 0 == remainingBytes
Function: ~WrappedVeloxMemoryPool
File: /mnt/disk1/oap-gluten/cpp/velox/memory/VeloxMemoryPool.cc
Line: 119
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZNSt23_Sp_counted_ptr_inplaceIN6gluten22WrappedVeloxMemoryPoolESaIS1_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
# 4  _ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv
# 5  _ZN8facebook5velox4exec4TaskD2Ev
# 6  _ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv
# 7  _ZZN8facebook5velox4exec9TableScan7preloadESt10shared_ptrINS0_9connector14ConnectorSplitEEENUlvE_D2Ev
# 8  _ZNSt17_Function_handlerIFSt10unique_ptrISt10shared_ptrIN8facebook5velox9connector10DataSourceEESt14default_deleteIS6_EEvEZNS3_4exec9TableScan7preloadES1_INS4_14ConnectorSplitEEEUlvE_E10_M_managerERSt9_Any_dataRKSH_St18_Manager_operation
# 9  _ZN8facebook5velox11AsyncSourceISt10shared_ptrINS0_9connector10DataSourceEEE7prepareEv
# 10 _ZN5folly6detail8function14FunctionTraitsIFvvEEclEv
# 11 _ZN5folly18ThreadPoolExecutor7runTaskERKSt10shared_ptrINS0_6ThreadEEONS0_4TaskE
# 12 _ZZN5folly20IOThreadPoolExecutor3addENS_8FunctionIFvvEEENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES3_ENUlvE_clEv
# 13 _ZN5folly6detail8function14FunctionTraitsIFvvEE7callBigIZNS_20IOThreadPoolExecutor3addENS_8FunctionIS3_EENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES8_EUlvE_EEvRNS1_4DataE
# 14 _ZN5folly6detail8function14FunctionTraitsIFvvEEclEv
# 15 _ZN5folly9EventBase10FuncRunnerclENS_8FunctionIFvvEEE
# 16 _ZN5folly6detail22invokeConsumerWithTaskINS_8FunctionIFvvEEERNS_9EventBase10FuncRunnerEvvvEENS_33AtomicNotificationQueueTaskStatusEOT0_OT_OSt10shared_ptrINS_14RequestContextEE
# 17 _ZN5folly23AtomicNotificationQueueINS_8FunctionIFvvEEEE5driveIRNS_9EventBase10FuncRunnerEEEbOT_
# 18 _ZN5folly32EventBaseAtomicNotificationQueueINS_8FunctionIFvvEEENS_9EventBase10FuncRunnerEE5driveIRS5_EEbOT_
# 19 _ZN5folly32EventBaseAtomicNotificationQueueINS_8FunctionIFvvEEENS_9EventBase10FuncRunnerEE7executeEv
# 20 _ZN5folly32EventBaseAtomicNotificationQueueINS_8FunctionIFvvEEENS_9EventBase10FuncRunnerEE12handlerReadyEt
# 21 _ZN5folly12EventHandler16libeventCallbackEisPv
```

### PR DESCRIPTION
**Pull request by Yohahaha**
Fix #1124 

Gluten should avoid the behavior may outlive the task, it breaks task execution model.

I'm not sure how performance boost can be gained from split preload, but I guess it gains little. When Velox has more suitable split preload mechanism that execute within lifecycle of task, we will consider open this feature then.

### CODE REVIEW

**Comment by Yohahaha** [comment]
@zhouyuan @FelixYBW Could you help take a look?

**Comment by FelixYBW** [comment]
@zhztheplayer what does InitCache(conf) do?

File: cpp/velox/compute/VeloxInitializer.cc [hunk 1]
```diff
@@ -112,18 +114,21 @@ void VeloxInitializer::Init(std::unordered_map<std::string, std::string>& conf)
   configurationValues.merge(S3Config);
 #endif
 
+  InitCache(conf);
+
   auto properties = std::make_shared<const velox::core::MemConfig>(configurationValues);
   auto hiveConnector =
       velox::connector::getConnectorFactory(velox::connector::hive::HiveConnectorFactory::kHiveConnectorName)
           ->newConnector(kHiveConnectorId, properties, ioExecutor_.get());
+  if (ioExecutor_) {
```
Comment (zhztheplayer) [inline cpp/velox/compute/VeloxInitializer.cc:123]: Folly has an Executor implementation `QueuedImmediateExecutor` which supports running job from caller thread. Did you have a try on something like that?

Comment (zhztheplayer) [reply cpp/velox/compute/VeloxInitializer.cc:123]: Or we must rely on async execution for works running on `ioExecutor_` and `ssdExecutor_` ?

**Comment by zhztheplayer** [comment]
> @zhztheplayer what does InitCache(conf) do?

I think it's for preparing some static stuffs for using local cache feature

File: cpp/velox/compute/VeloxInitializer.cc (hunk 1 above)
Comment (Yohahaha) [reply cpp/velox/compute/VeloxInitializer.cc:123]: I'm not sure what you say, have you take a look for #1124 ? split preload logic in inside Velox, I think Gluten can use `QueuedImmediateExecutor ` to control it.

**Comment by Yohahaha** [comment]
> @zhztheplayer what does InitCache(conf) do?

It's another PR, move `InitCache` location before access `ioExecutor` avoid nullptr.

**Review by zhouyuan — APPROVED** [review]
👍

File: cpp/velox/compute/VeloxInitializer.cc (hunk 1 above)
Comment (zhouyuan) [reply cpp/velox/compute/VeloxInitializer.cc:123]: @zhztheplayer yes, this patch fixes a bug in main branch

Comment (zhztheplayer) [reply cpp/velox/compute/VeloxInitializer.cc:123]: @Yohahaha `folly::IOThreadPoolExecutor` is just an implementation of `folly::Executor`. Is this possible to use `folly::QueuedImmediateExecutor` to replace `folly::IOThreadPoolExecutor` to avoid Velox's async calls?
