### PR TITLE
[GLUTEN-10635][VL] bugfix: file INSTALL cannot set permissions

### LINKED ISSUE #10635: [VL] file INSTALL cannot set permissions
### Backend

VL (Velox)

### Bug description

I build Gluten 1.4 successfully.
But when I building the latest gluten, I found the error show below.
```
-- Found Backtrace: /usr/include  
-- ---------------------------------------------------------------------
-- Arrow version:                                 15.0.0
-- 
-- Build configuration summary:
--   Generator: Ninja
--   Build type: RELEASE
--   Source directory: /home/hadoop/gluten/ep/_ep/arrow_ep/cpp
--   Install prefix: /usr/local
-- 
-- Compile and link options:
-- 
--   ARROW_CXXFLAGS="" [default=""]
--       Compiler flags to append when compiling Arrow
--   ARROW_BUILD_STATIC=ON [default=ON]
--       Build static libraries
--   ARROW_BUILD_SHARED=OFF [default=ON]
--       Build shared libraries
--   ARROW_PACKAGE_KIND="" [default=""]
--       Arbitrary string that identifies the kind of package
--       (for informational purposes)
--   ARROW_GIT_ID=84ac41874ce027ef66bc9f13881e1dfe105206c3 [default=""]
--       The Arrow git commit id (if any)
--   ARROW_GIT_DESCRIPTION="" [default=""]
--       The Arrow git commit description (if any)
--   ARROW_NO_DEPRECATED_API=OFF [default=OFF]
--       Exclude deprecated APIs from build
--   ARROW_POSITION_INDEPENDENT_CODE=ON [default=ON]
--       Whether to create position-independent target
--   ARROW_USE_CCACHE=ON [default=ON]
--       Use ccache when compiling (if available)
--   ARROW_USE_SCCACHE=ON [default=ON]
--       Use sccache when compiling (if available),
--       takes precedence over ccache if a storage backend is configured
--   ARROW_USE_LD_GOLD=OFF [default=OFF]
--       Use ld.gold for linking on Linux (if available)
--   ARROW_USE_PRECOMPILED_HEADERS=OFF [default=OFF]
--       Use precompiled headers when compiling
--   ARROW_SIMD_LEVEL=NONE [default=DEFAULT|NONE|SSE4_2|AVX2|AVX512|NEON|SVE|SVE128|SVE256|SVE512]
--       Compile-time SIMD optimization level
--   ARROW_RUNTIME_SIMD_LEVEL=NONE [default=MAX|NONE|SSE4_2|AVX2|AVX512]
--       Max runtime SIMD optimization level
--   ARROW_ALTIVEC=ON [default=ON]
--       Build with Altivec if compiler has support
--   ARROW_RPATH_ORIGIN=OFF [default=OFF]
--       Build Arrow libraries with RATH set to $ORIGIN
--   ARROW_INSTALL_NAME_RPATH=ON [default=ON]
--       Build Arrow libraries with install_name set to @rpath
--   ARROW_GGDB_DEBUG=ON [default=ON]
--       Pass -ggdb flag to debug builds
--   ARROW_WITH_MUSL=OFF [default=OFF]
--       Whether the system libc is musl or not
--   ARROW_ENABLE_THREADING=ON [default=ON]
--       Enable threading in Arrow core
-- 
// ignore other log
-- Advanced developer options:
-- 
--   ARROW_EXTRA_ERROR_CONTEXT=OFF [default=OFF]
--       Compile with extra error context (line numbers, code)
--   ARROW_OPTIONAL_INSTALL=OFF [default=OFF]
--       If enabled install ONLY targets that have already been built. Please be
--       advised that if this is enabled 'install' will fail silently on components
--       that have not been built
--   ARROW_GDB_INSTALL_DIR="" [default=""]
--       Use a custom install directory for GDB plugin.
--       In general, you don't need to specify this because the default
--       (CMAKE_INSTALL_FULL_BINDIR on Windows, CMAKE_INSTALL_FULL_LIBDIR otherwise)
--       is reasonable.
--   Outputting build configuration summary to /home/hadoop/gluten/ep/_ep/arrow_ep/cpp/_build/cmake_summary.json
-- Configuring done (3.3s)
-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING


-- Build files have been written to: /home/hadoop/gluten/ep/_ep/arrow_ep/cpp/_build
++ echo 'we will build with cmake'
we will build with cmake
++ cmake --build _build
[272/272] Linking CXX static library release/libarrow_testing.a
++ cmake --install _build
-- Install configuration: "RELEASE"
-- Up-to-date: /usr/local/include/arrow-gtest
CMake Error at _build/cmake_install.cmake:51 (file):
  file INSTALL cannot set permissions on "/usr/local/include/arrow-gtest":
  Operation not permitted.
```

### Gluten version

main branch

### Spark version

Spark-3.2.x

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

```bash

```

### PR DESCRIPTION
**Pull request by beliefer**
## What changes are proposed in this pull request?

This PR proposes to fix a building bug.
Fixes #10635

## How was this patch tested?

GA tests.

### CODE REVIEW

**Comment by Zouxxyy** [comment]
I actually encountered this problem when running `build_arrow` on my Mac, and I was confused as to why arrow was installed in a fixed location  like this `cmake --install ./ --prefix /usr/local/`. Instead of using `INSTALL_PREFIX`

```shell
if [[ "$(uname)" == "Darwin" ]]; then
    INSTALL_PREFIX=${INSTALL_PREFIX:-${VELOX_HOME}/deps-install}
else
    INSTALL_PREFIX=${INSTALL_PREFIX:-"/usr/local"}
fi
```

Maybe we need a fix? @zhouyuan

**Comment by philo-he** [comment]
@Zouxxyy, MacOS was not properly considered in the Arrow installation. You can propose a fix to use a path more suitable for MacOS. Maybe, you can just replace `/usr/local` with `$INSTALL_PREFIX` in build_arrow.sh.

File: dev/build_helper_functions.sh [hunk 1]
```diff
@@ -137,6 +137,11 @@ function cmake_install {
     "$@"
 
   cmake --build "${BINARY_DIR}"
+  if [ -z "${SUDO}" ]; then
+    if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
+      SUDO="sudo"
```
Comment (philo-he) [inline dev/build_helper_functions.sh]: Can we just let user fix this issue by setting `SUDO=sudo` in the environment?

**Comment by Zouxxyy** [comment]
> @Zouxxyy, MacOS was not properly considered in the Arrow installation. You can propose a fix to use a path more suitable for MacOS. Maybe, you can just replace `/usr/local` with `$INSTALL_PREFIX` in build_arrow.sh.

Sure, can you have a look at https://github.com/apache/incubator-gluten/pull/10650, thanks

File: dev/build_helper_functions.sh (hunk 1 above)
Comment (beliefer) [reply dev/build_helper_functions.sh]: Thank you! I tried in this way. But it is still not working.

Comment (zhouyuan) [reply dev/build_helper_functions.sh]: Can you pease try to add this line in the beginning of this file?
https://github.com/apache/incubator-gluten/blob/main/dev/build_arrow.sh#L21

Comment (beliefer) [reply dev/build_helper_functions.sh]: Done.

Comment (philo-he) [reply dev/build_helper_functions.sh]: It seems line 21 should be changed to `SUDO="${SUDO:-""}"`, where all letters are capitalized. Then, I assume setting `SUDO=sudo` in the environment should work.

Comment (beliefer) [reply dev/build_helper_functions.sh]: > It seems line 21 should be changed to `SUDO="${SUDO:-""}"`, where all letters are capitalized. Then, I assume setting `SUDO=sudo` in the environment should work.

I tried this way, it works well. But I don't know if it will affect other OS.

Comment (philo-he) [reply dev/build_helper_functions.sh]: @beliefer, I suggest to just fix this line, and let users explicitly set the environment variable if they meet such permission issue.

**Comment by beliefer** [comment]
@PHILO-HE @zhouyuan Thank you!
