### PR TITLE
[GLUTEN-1866][CORE] Fix a NPE in creating gluten executor endpoint

### LINKED ISSUE #1866: netty Error in gluten
**Describe the bug**
2023-06-06 23:16:35,898 ERROR netty.Inbox: Ignoring error
java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3039)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.spark.rpc.RpcEndpointAddress$.apply(RpcEndpointAddress.scala:55)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:140)
	at org.apache.spark.rpc.GlutenExecutorEndpoint.onStart(GlutenExecutorEndpoint.scala:48)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:120)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:213)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:100)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:75)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Some problem when run the velox backend with gluten 0.5.0

### PR DESCRIPTION
**Pull request by wForget**
## What changes were proposed in this pull request?

close #1866

### CODE REVIEW

File: gluten-core/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala [hunk 1]
```diff
@@ -33,16 +33,16 @@ class GlutenExecutorEndpoint(val executorId: String, val conf: SparkConf)
...
-    rpcEnv.setupEndpoint(GlutenRpcConstants.GLUTEN_EXECUTOR_ENDPOINT_NAME, this)
-
   private val driverHost = conf.get(config.DRIVER_HOST_ADDRESS.key, "localhost")
   private val driverPort = conf.getInt(config.DRIVER_PORT.key, 7077)
   private val driverUrl =
     s"spark://${GlutenRpcConstants.GLUTEN_DRIVER_ENDPOINT_NAME}@$driverHost:$driverPort"
 
   @volatile var driverEndpointRef: RpcEndpointRef = null
 
+  val executorEndpoint: RpcEndpointRef =
```
Comment (PHILO-HE) [inline gluten-core/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala:43]: Can we remove `val executorEndpoint: RpcEndpointRef =`? Looks useless. Thanks!

Comment (wForget) [reply gluten-core/src/main/scala/org/apache/spark/rpc/GlutenExecutorEndpoint.scala]: thanks, removed

**Review by PHILO-HE — APPROVED** [review]
