### PR TITLE
[GLUTEN-3480] Fix incorrect metrics values for ch backend

### LINKED ISSUE #3480: Fix incorrect metrics values for ch backend
### Backend

CH (ClickHouse)

### Bug description

Fix incorrect metrics values for ch backend:
1. When there is a r2c operation, it will call `iter.hasNext` more than once, so the native metrics will be added more than once;
2. Add the `resize` metrics for ch agg operation.

### Spark version

None

### Spark configurations

_No response_

### System information

_No response_

### Relevant logs

_No response_

### PR DESCRIPTION
**Pull request by zzcclp**
## What changes were proposed in this pull request?

Fix incorrect metrics values for ch backend:
1. When there is a r2c operation, it will call iter.hasNext more than once, so the native metrics will be added more than once;
2. Add the resize metrics for ch agg operation.

Close #3480.

(Fixes: #3480)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

File: backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala [hunk 1]
```diff
@@ -132,14 +132,17 @@ class CHIteratorApi extends IteratorApi with Logging with LogLevelUtil {
       private val inputMetrics = TaskContext.get().taskMetrics().inputMetrics
       private var outputRowCount = 0L
       private var outputVectorCount = 0L
+      private var metricsUpdated = false
 
       override def hasNext: Boolean = {
         val res = resIter.hasNext
-        if (!res) {
+        // avoid to collect native metrics more than once, 'hasNext' is a idempotent operation
+        if (!res && !metricsUpdated) {
```
Comment (baibaichen) [inline backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala:140]: 额外加个函数是不是可读性更好？

```scala
val hasResult = resIter.hasNext
def needUpdateMetrtics(): boolean = {
    !(hasResult || metricsUpdated)
}
```

Comment (zzcclp) [reply backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala:140]: IMO don't have to

Comment (baibaichen) [reply backends-clickhouse/src/main/scala/io/glutenproject/backendsapi/clickhouse/CHIteratorApi.scala:140]: `if (!res && !metricsUpdated)` 这种比较费解。

看起来 `metricsUpdated` 只在` !res && !metricsUpdated` 为真的时候被更新，似乎没有必要？

**Review by baibaichen — APPROVED** [review]
